version: "3"

services:
  # PostgreSQL service
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data

  # Node API service
  api:
    build: ./
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgresdb

volumes:
  pg-data:
    driver: local
